global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9090']

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  - job_name: 'Scoutastic-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.10:9090']
    
  # - job_name: 'nginx-exporter'
  #   static_configs:
  #     - targets: ['nginx_exporter:9113']
  
  # - job_name: 'odoo-server'
  #   http_sd_configs:
  #     - url: "http://192.168.56.10:8069/web"
  #     ca_file: /etc/prometheus/cert/host1/ca-crt.pem
  #     cert_file: /etc/prometheus/cert/host1/client-crt.pem
  #     key_file: /etc/prometheus/cert/host1/client-key.pem
  #   static_configs:
  #     - targets:
  #       - 192.168.56.10:8069