global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: 'pce'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/host1/prometheus-example-ca-crt.pem
      cert_file: /etc/prometheus/cert/host1/host1.key.pem
      key_file: /etc/prometheus/cert/host1/host1.key.pem
    static_configs:
      - targets:
        - 192.168.56.10:8069